src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index as Index;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 * @ORM\Table(name="videos", indexes={@Index(name="title_idx", columns={"title"})})
 */
class Video
{
//    public const videoForNotLoggedInOrNoMembers = '113716040';
    public const videoForNotLoggedInOrNoMembers = 'https://player.vimeo.com/video/113716040';
    public const VimeoPath = 'https://player.vimeo.com/video/';
    public const perPage = 5; // pagination
    public const uploadFolder = 'uploads/videos/';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="videos")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="video")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="likedVideos")
     * @ORM\JoinTable(name="likes")
     */
    private $usersThatLike;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="dislikedVideos")
     * @ORM\JoinTable(name="dislikes")
     */
    private $usersThatDontLike;

    /**
     * @Assert\NotBlank(message="Please, upload the video as a MP4 file.")
     * @Assert\File(mimeTypes={ "video/mp4" })
     */
    private $uploaded_video;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->usersThatLike = new ArrayCollection();
        $this->usersThatDontLike = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function getPathUrl(): ?string
    {
        if (strpos($this->path, self::uploadFolder) !== false) {
            return '/'.$this->path;
        }
        return $this->path;
    }

/*    public function getVimeoId(): ?string
    {
       return $this->path;
    } */
    public function getVimeoId(): ?string
    {
       if (strpos($this->path, self::uploadFolder) !== false) {
           return $this->path;
       }
       $array = explode('/', $this->path);
         return end($array);
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setVideo($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsersThatLike(): Collection
    {
        return $this->usersThatLike;
    }

    public function addUsersThatLike(User $usersThatLike): self
    {
        if (!$this->usersThatLike->contains($usersThatLike)) {
            $this->usersThatLike[] = $usersThatLike;
        }

        return $this;
    }

    public function removeUsersThatLike(User $usersThatLike): self
    {
        if ($this->usersThatLike->contains($usersThatLike)) {
            $this->usersThatLike->removeElement($usersThatLike);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsersThatDontLike(): Collection
    {
        return $this->usersThatDontLike;
    }

    public function addUsersThatDontLike(User $usersThatDontLike): self
    {
        if (!$this->usersThatDontLike->contains($usersThatDontLike)) {
            $this->usersThatDontLike[] = $usersThatDontLike;
        }

        return $this;
    }

    public function removeUsersThatDontLike(User $usersThatDontLike): self
    {
        if ($this->usersThatDontLike->contains($usersThatDontLike)) {
            $this->usersThatDontLike->removeElement($usersThatDontLike);
        }

        return $this;
    }

    public function getUploadedVideo()
    {
        return $this->uploaded_video;
    }

    public function setUploadedVideo($uploaded_video): self
    {
        $this->uploaded_video = $uploaded_video;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Controller\Traits\Likes;
use App\Utils\Interfaces\CacheInterface;
use App\Utils\VideoForNoValidSubscription;
use App\Entity\Category;
use App\Entity\Comment;
use App\Entity\User;
use App\Entity\Video;
use App\Form\UserType;
use App\Repository\VideoRepository;
use App\Utils\CategoryTreeFrontPage;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class FrontController extends AbstractController
{
    use Likes;

    /**
     * @Route("/", name="main_page")
     */
    public function index()
    {
        return $this->render('front/index.html.twig');
    }

    /**
     * @Route("/video-list/category/{categoryname},{id}/{page}", name="video_list",
     * defaults={"page": "1"})
     */
    public function videoList($id, $page, CategoryTreeFrontPage $categories, Request $request, VideoForNoValidSubscription $videoNoMembers, CacheInterface $cache)
    {
        $cache = $cache->cache;
        $video_list = $cache->getItem('video_list'.$id.$page.$request->get('sortby'));
        // $video_list->tag(['video_list']);
        $video_list->expiresAfter(60);


        if(!$video_list->isHit()) {
            $categories->getCategoryListAndParent($id);
            $ids = $categories->getChildIds($id);
            array_push($ids, $id);
            $videos = $this->getDoctrine()->getRepository(Video::class)->findByChildIds($ids, $page, $request->get('sortby'));
            $response = $this->render('front/video_list.html.twig', [
                'subcategories' => $categories,
                'videos' => $videos,
                'videoNoMembers' => $videoNoMembers->check(),
            ]);
            $video_list->set($response);
            $cache->save($video_list);
        }
        return $video_list->get();

    }

    /**
     * @Route("/video-details/{video}", name="video_details")
     */
    public function videoDetails(VideoRepository $repository, $video, VideoForNoValidSubscription $videoNoMembers)
    {
        return $this->render('front/video_details.html.twig', [
            'video' => $repository->videoDetails($video),
            'videoNoMembers' => $videoNoMembers->check(),
        ]);
    }

    /**
     * @Route("/video-list/{video}/like", name="like_video", methods={"POST"})
     * @Route("/video-list/{video}/dislike", name="dislike_video", methods={"POST"})
     * @Route("/video-list/{video}/unlike", name="undo_like_video", methods={"POST"})
     * @Route("/video-list/{video}/undodislike", name="undo_dislike_video", methods={"POST"})
     */
    public function toggleLikesAjax(Video $video, Request $request)
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');

        switch ($request->get('_route')) {
            case 'like_video':
                $result = $this->likeVideo($video);
                break;

            case 'dislike_video':
                $result = $this->dislikeVideo($video);
                break;

            case 'undo_like_video':
                $result = $this->undoLikeVideo($video);
                break;

            case 'undo_dislike_video':
                $result = $this->undoDislikeVideo($video);
                break;
        }

        return $this->json(['action' => $result, 'id' => $video->getId()]);
    }


    /**
     * @Route("/new-comment/{video}", name="new_comment")
     */
    public function newComment(Request $request, Video $video)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        if (!empty(trim($request->request->get('comment')))) {
            $comment = new Comment;
            $comment->setUser($this->getUser());
            $comment->setVideo($video);
            $comment->setContent($request->request->get('comment'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
        }
        return $this->redirectToRoute('video_details', ['video' => $video->getId()]);
    }


    /**
     * @Route("/search-results/{page}", methods={"GET"}, name="search_results",
     * defaults={"page": "1"})
     */
    public function searchResults(Request $request, $page = 1, VideoForNoValidSubscription $videoNoMembers)
    {
        $videos = null;
        $query = null;
        if ($query = $request->get('query')) {
            $videos = $this->getDoctrine()->getRepository(Video::class)->findByTitle($query, $page, $request->get('sortby'));
            if (!$videos->getItems()) $videos = null;
        }


        return $this->render('front/search_results.html.twig', [
            'videos' => $videos,
            'query' => $query,
            'videoNoMembers' => $videoNoMembers->check(),
        ]);
    }






    public function mainCategories()
    {
        $categories = $this->getDoctrine()->getRepository(Category::class)->findBy(['parent' => null], ['name' => 'ASC']);
        return $this->render('front/_main_categories.html.twig', [
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/delete-comment/{comment}", name="delete_comment")
     * @Security("user.getId() == comment.getUser().getId()")
     */
    public function deleteComment(Comment $comment, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        $em = $this->getDoctrine()->getManager();
        $em->remove($comment);
        $em->flush();
        return $this->redirect($request->headers->get('referer'));
    }
}

templates/front/_main_categories.html.twig
{#                <a class="p-2 text-dark" href="{{ path('video_list') }}">Funny</a>
                <a class="p-2 text-dark" href="{{ path('video_list') }}">Scary</a>
                <a class="p-2 text-dark" href="{{ path('video_list') }}">Unbelievable</a>
                <a class="p-2 text-dark" href="{{ path('video_list') }}">Inspirational</a>
                <a class="p-2 text-dark" href="{{ path('video_list') }}">Motivating</a>#}

{% for category  in categories %}
    <a class="p-2 text-dark" href="{{ path('video_list', {'categoryname':category.name|slugify, 'id':category.id}) }}">{{ category.name }}</a>
{% endfor %}

templates/front/index.html.twig
{% extends 'base.html.twig' %}
{% block main %}

<h1 class="text-info mb-5 mt-4">Where the best videos happens</h1>

<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/137857207" allowfullscreen></iframe>
</div>
{% endblock %}

templates/front/login.html.twig
{% extends 'base.html.twig' %}
{% block customstylesheets %}
<link rel="stylesheet" href="{{ asset('assets/css/login.css') }}">
{% endblock %}
{% block menu %}{% endblock %}
{% block main %}
    {% if error %}
        <div class="alert alert-danger">
            {{ error.messageKey|trans(error.messageData, 'security') }}
        </div>
    {% endif %}
<form method="POST" action="{{ path('login') }}" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input name="_email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input name="_password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" name="_remember_me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2018 <a href="{{ path('main_page') }}">main page</a></p>
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
</form>
{% block footer_links %}{% endblock %}
{% endblock %}

templates/front/payment.html.twig
{% extends 'base.html.twig' %}
{% block main %}
<div class="row mt-5">
    <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ app.session.get('planName')}} plan</h6>
                </div>
                <span class="text-muted">${{ app.session.get('planPrice')}}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>EXAMPLECODE</small>
                </div>
                <span class="text-success">-$0</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <strong>${{ app.session.get('planPrice')}}</strong>
            </li>
        </ul>
    </div>

    <div class="col-md-8 order-md-1">

        <h4 class="mb-3">Pay with PayPal <small>or get other <a href="{{ path('pricing') }}">plan</a></small></h4>
        <hr class="mb-4">
        <a href="{{ path('payment', {'paypal':'patpal'}) }}" class="btn btn-primary btn-lg btn-block" role="button">Continue to checkout</a>

    </div>
</div>
{% endblock %}

templates/front/pricing.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Watch the best videos on the planet. Choose a plan that is right for you. Downgrade or upgrade at
        any time.
    </p>
</div>

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ name[0]|capitalize }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ price[name[0]]}} <small class="text-muted">/ mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Access for one month</li>
                    <li>Help center access</li>
                </ul>
                <a role="button" href="{{ path('register', {'plan':name[0]}) }}" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</a>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ name[1]|capitalize }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ price[name[1]] }} <small class="text-muted">/ mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Unlimited access</li>
                    <li>HD available</li>
                    <li>No ads on videos</li>
                    <li>Help center access</li>
                </ul>
                <a role="button" href="{{ path('register', {'plan':name[1]}) }}" class="btn btn-lg btn-block btn-primary">Get started</a>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ name[2]|capitalize }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ price[name[2]]}} <small class="text-muted">/ mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Unlimited access</li>
                    <li>Ultra HD available</li>
                    <li>No ads on videos</li>
                    <li>Help center access</li>
                    <li>Unlimited live events</li>
                </ul>
                <a role="button" href="{{ path('register', {'plan':name[2]}) }}" class="btn btn-lg btn-block btn-primary">Contact us</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/front/register.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<div class="row mt-5">
    <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ app.session.get('planName')}} plan</h6>
                </div>
                <span class="text-muted">${{ app.session.get('planPrice')}}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>EXAMPLECODE</small>
                </div>
                <span class="text-success">-$0</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <strong>${{ app.session.get('planPrice')}}</strong>
            </li>
        </ul>
    </div>

    <div class="col-md-8 order-md-1">
        <h4 class="mb-3">Register first (free)</h4>
{#        <form method="POST" action="#" class="needs-validation" novalidate>#}
        {{ form_start(form, {'attr': {'class':"needs-validation" }}) }}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="user_name">First name</label>
{#                    <input type="text" class="form-control" id="firstName" placeholder="" value="" required>#}
                    {{ form_widget(form.name) }}
                    <div class="invalid-feedback">
                        Valid first name is required.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="user_name_name">Last name</label>
{#                    <input type="text" class="form-control" id="lastName" placeholder="" value="" required>#}
                    {{ form_widget(form.last_name) }}
                    <div class="invalid-feedback">
                        Valid last name is required.
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="user_email">Email</label>
{#                <input type="email" class="form-control" id="email" placeholder="you@example.com" required>#}
                {{ form_widget(form.email) }}

                <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                </div>
            </div>

            <div class="mb-3">
                <label for="user_password_first">Password</label>
{#                <input type="password" class="form-control" id="password" required>#}
                {{ form_widget(form.password.first) }}

                <div class="invalid-feedback">
                    Please enter a valid password (min 6 characters).
                </div>
            </div>

            <div class="mb-3">
                <label for="user_password_second">Confirm Password</label>
{#                <input type="password" class="form-control" id="confirm_password" required>#}
                {{ form_widget(form.password.second) }}

                <div class="invalid-feedback">
                    Please enter a valid password confirmation (min 6 characters).
                </div>
            </div>

            <hr class="mb-4">
        <button type="submit" class="btn btn-primary btn-lg btn-block">Register</button>
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

{% block customjavascripts %}
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';

        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');

            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('click', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();


    var password = document.getElementById("user_password_first"), confirm_password = document.getElementById("user_password_second");

    function validatePassword() {
        if (password.value != confirm_password.value) {
            confirm_password.setCustomValidity("Passwords Don't Match");
        } else {
            confirm_password.setCustomValidity('');
        }
    }
    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;
</script>

{% endblock %}

templates/front/search_results.html.twig
{% extends 'base.html.twig' %}

{% block customstylesheets %}
    {{parent()}}
    {% if app.user %}
        <link rel="stylesheet" href="{{asset('assets/css/likes.css')}}">
    {% endif %}
{% endblock %}

{% block main %}
    <section class="jumbotron text-center">
        <div class="container">
            {% if videos %}
                <h1 class="jumbotron-heading">Search results</h1>
                {{ include('front/includes/_sort.html.twig',{'query':query}) }}
            {% else %}
                <h1 class="jumbotron-heading">No results were found</h1>
            {% endif %}
        </div>
    </section>
    {% if videos %}
        {{ include('front/includes/_videos.html.twig', {'videos' : videos}) }}
        {{ knp_pagination_render(videos) }}
    {% endif %}
{% endblock %}
{% block customjavascripts %}
    {{parent()}}
    {% if app.user %}
        <script src="{{asset('assets/js/likes.js')}}"></script>
    {% endif %}
{% endblock %}

templates/front/video_details.html.twig
{% extends 'base.html.twig' %}
        {% if videoNoMembers is not null %}
{#            {% set videoid = 'https://player.vimeo.com/video/' ~ videoNoMembers %}#}
            {% set videoid = videoNoMembers %}
        {% else %}
{#            {% set videoid = video.vimeoid %}#}
{#            if video.path have "uploads/videos" in strong#}
            {% set videoid =  video.pathUrl %}

        {% endif %}
{% block main %}
<br>
<h1>{{ video.title }}</h1>
<div align="center" class="embed-responsive embed-responsive-16by9">
    <iframe class="" src="{{ videoid }}" frameborder="0" allowfullscreen></iframe>
</div>

<hr>

<div class="row m-2">
    <a id="video_comments"></a>
    <ul class="list-unstyled text-left">

    {%  for comment in video.comments %}

        <li class="media">
            <img class="mr-3" src="{{ asset('assets/img/user.jpg') }}" alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0 mb-1"><b>{{ comment.user.name }} {{ comment.user.lastname }}</b> <small class="text-muted">added a comment <small><b>{{ comment.createdat|ago }}</b></small></small></h5>
                {{ comment.content }}
                {% if app.user and app.user.id == comment.user.id %}
                <a href="{{ path('delete_comment',{'comment':comment.id}) }}" class="btn btn-danger btn-sm">Delete comment</a>
                {% endif %}
            </div>
        </li>

        <hr>

    {% endfor %}
    </ul>
</div>

<div class="row">
    <div class="col-md-12">
        <form method="POST" action="{{ path('new_comment',{'video':video.id}) }}#video_comments">
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Add a comment</label>
                <textarea name="comment" required class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Add</button>

        </form>
    </div>
</div>



{% endblock %}

templates/front/video_list.html.twig
{% extends 'base.html.twig' %}
{% block customstylesheets %}
    {{ parent() }}
    {% if app.user %}
        <link rel="stylesheet" href="{{ asset('assets/css/likes.css') }}">
    {% endif %}
{% endblock %}
{% block main %}

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">

            <h1 class="jumbotron-heading">Category - {{ subcategories.currentCategoryName }}</h1>
            <div class="btn-group">
                <div class="dropdown ml-2">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Subcategories
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <ul class="mr-5">
                            <li><a href="{{ path('video_list', {'categoryname':subcategories.mainParentName|slugify|lower, 'id': subcategories.mainParentId}) }}">{{ subcategories.mainParentName }}</a></li>
                            {{ subcategories.categoryList|raw }}
                        </ul>
                    </div>
                </div>

                <div class="form-row align-items-center ml-3">
                    {{ include('front/includes/_sort.html.twig', {'videos' : videos}) }}
                </div>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {{ include('front/includes/_videos.html.twig', {'videos' : videos}) }}
            </div>
        </div>
    </div>

    <!-- pagination -->
    {{ knp_pagination_render(videos) }}


</main>
{% endblock %}
{% block customjavascripts %}
    {{ parent()}}
    {% if app.user %}
        <script src="{{ asset('assets/js/likes.js') }}"></script>
    {% endif %}
{% endblock %}